### ISSUE TITLE
python mange.py makemigrations chat

### ISSUE THREAD

**Issue by asuresh1** [Cloud-CV/visual-chatbot#14]
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/suresha1/anaconda3/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/suresha1/anaconda3/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/home/suresha1/anaconda3/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/suresha1/anaconda3/lib/python3.7/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/home/suresha1/anaconda3/lib/python3.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/suresha1/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/suresha1/torch/pytorch/visual-chatbot/chat/models.py", line 20, in <module>
    class Dialog(models.Model):
  File "/home/suresha1/torch/pytorch/visual-chatbot/chat/models.py", line 22, in Dialog
    job = models.ForeignKey(Job)
TypeError: __init__() missing 1 required positional argument: 'on_delete'

**Comment by deshraj** [comment]
@asuresh1 can you please tell me the version of django that you are using? Then I will be able to assist you in a better way.

**Comment by asuresh1** [comment]
Deshraj,
   I am using Python 3.7 and Django django.VERSION
(2, 1, 5, 'final', 0)

**Comment by deshraj** [comment]
Please use the django version mentioned here: https://github.com/Cloud-CV/visual-chatbot/blob/master/requirements.txt#L2

There are some breaking changes in django 2.x which is not compatible with Visual Chatbot codebase.
